### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ngoldbaum** [zero-py/thingking#1]
```
Collecting thingking==1.1.0 (from -r tests/test_requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/d9/75/731239771b31431cfd376b43533347a77d54df7e3c40423612ccfeec8ff2/thingking-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-80c3kyzh/thingking/setup.py", line 13, in <module>
        modules = cythonize(extensions)
      File "/home/travis/build/yt-project/yt/venv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 956, in cythonize
        aliases=aliases)
      File "/home/travis/build/yt-project/yt/venv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 801, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/travis/build/yt-project/yt/venv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'thingking/pagefault.pyx' doesn't match any files
```

Probably a packaging issue with the tarball.

**Comment by matthewturk** [comment]
Should be fixed in 1.1.1 and on master.  Thanks!
